# Entrypoint for all checks
name: all-checks

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - 'main'
      - 'releases/**'
    paths-ignore:
      - "**.md"
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "**.md"
  release:
    types:
      - created

  # Allow manual execution of the checks
  workflow_dispatch:

jobs:
  yamllint:
    uses: ./.github/workflows/yamllint.yml

  docker:
    uses: ./.github/workflows/docker.yml
    if: success() && github.ref == 'refs/heads/main'
    needs: yamllint
    secrets: inherit
